language: cpp

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET_CPU=x64
    addons:
      apt: &x64-apt
        packages:
        - libglib2.0-dev
        - libgtk2.0-dev
        - libxtst-dev
        - libxss-dev
        - libpci-dev
        - libdbus-1-dev
        - libgconf2-dev
        - libgnome-keyring-dev
        - libnss3-dev
        - libasound2-dev
        - libpulse-dev
        - libudev-dev
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET_CPU=x64 CMAKE_BUILD_TYPE=Debug
    addons:
      apt: *x64-apt
  - os: osx
    osx_image: xcode7.3
    env: TARGET_CPU=x64
  - os: osx
    osx_image: xcode7.3
    env: TARGET_CPU=x64 CMAKE_BUILD_TYPE=Debug

before_install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  else
    if ! brew ls --version cmake &>/dev/null; then brew update && brew install cmake; fi
  fi
- cd ${TRAVIS_BUILD_DIR}
- cmake --version

install:
- git submodule init
- git submodule update
- mkdir out
- cd out
- cmake -DBUILD_SAMPLE=1 -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=. -DTARGET_CPU=$TARGET_CPU ..

script:
- make -j 4 package

before_deploy:
- export TRAVIS_ARTIFACTS=$(ls libwebrtc-*.tar.gz)

deploy:
  provider: releases
  api_key:
    secure: "rZsKJiH11w/YAOQN5P1hfRsl83C7jgZpAgEfbZHh1ShaXQgA5cNe4ySOha7bn4BiWqbf7N2tQLovyatxy7hy2ef0QcWlU8aNjaAWE/Tzjy+hHvWD2Q2Q+dpKDp0+ZDHxIt8hjvLJsnxk8pkLI0zJsU20LH6TFVpyxSLwrj+iADxL4FI69Jh1HnbVwHBKOVrcGjTSXughRDXJ7VNYw6K1eg+D8x5d3jtsYg8TGpGYdhR9AaQIcvQo7octLavs0FesxDgJyczRMpGhxzGd9+VC970s+NSgrcKBIl3Yi9WqI06+5bolR3fbR4Hm3kaQzQVg5WMLRzGOWnDKDm30FzFruG+8MqdMyy0rUfzkcMPbhddDrVWnC929TsIsgrcr1TXpfp+YVShgon6siMJH21Wa1BM+Al1qf5HNjb/LlfRiJkoXdl4tLkvDzHve9vvpbaXzYC9/0whHi0W5f7oKmMtSnVtMyRxEvTMInImmMTcSwxi2EkeG9ts3fda22XUeb96qzck+9DVBZlMHkFMY3FAOhzF7xO9OB0m0olCL26nD7LU2uI5F9fdeOh0hkErRRAuxApqFav7r8t0CXCTLvZw6FzGgOCGj0LCg91z4ocpv9wQ+n0ZSbNVZLZkThmZnnstFo3gQk6mu5l4k82qUXRwLh7wf6UwJIeTgTIvejam2s8M="
  file_glob: true
  file: "${TRAVIS_ARTIFACTS}"
  skip_cleanup: true
  on:
    tags: true
    repo: mayeut/libwebrtc
